@startuml

class Pets{
  age()
  color()
  pets_nutered

}

class Pets extends Species {

}

class Breed extends Species {
  BreedID()
  BreedName()
  SpeciesID()
  PureBred()
  MixedBreed()
_construct()
get_breed_ID()
get_breed_name()
get_breed_isPure()
get_breed_isMixed
}

class Species {
  SpeciesID()
  SpeciesName()
  _construct()
get_species_id()
get_species_name
}

class Toys {
  ToysID()
  ToysName()
  BestFor()
_construct()
get_toys_ID()
}

class Pricing extends Toys{
  ItemID()
  ItemType()
  Cost()
  OnSale()
_construct()
}


@enduml


<!--life expectencies/maintance-->